// domain/shop/index.ts

export {
  ORDER_STATUS_PENDING,
  ORDER_STATUS_AWAITING_PAYMENT,
  ORDER_STATUS_PAID,
  ORDER_STATUS_SHIPPED,
  ORDER_STATUS_DELIVERED,
  ORDER_STATUS_CANCELLED,
  ORDER_PAYMENT_PROVIDER_STRIPE,
  ORDER_PAYMENT_STATUS_OPEN,
  ORDER_PAYMENT_STATUS_PAID,
  ORDER_PAYMENT_STATUS_FAILED,
  ORDER_PAYMENT_STATUS_EXPIRED,
  ORDER_PAYMENT_STATUS_PARTIALLY_REFUNDED,
  ORDER_PAYMENT_STATUS_REFUNDED,
  ORDER_REFUND_STATUS_PENDING,
  ORDER_REFUND_STATUS_SUCCEEDED,
  ORDER_REFUND_STATUS_FAILED,
  ORDER_REFUND_STATUS_CANCELED,
  ORDER_DISPUTE_STATUS_WARNING_NEEDS_RESPONSE,
  ORDER_DISPUTE_STATUS_WARNING_UNDER_REVIEW,
  ORDER_DISPUTE_STATUS_WARNING_CLOSED,
  ORDER_DISPUTE_STATUS_NEEDS_RESPONSE,
  ORDER_DISPUTE_STATUS_UNDER_REVIEW,
  ORDER_DISPUTE_STATUS_WON,
  ORDER_DISPUTE_STATUS_LOST,
  ORDER_WITH_ITEMS_QUERY,
  getProducts,
  getProductById,
  createProduct,
  updateProduct,
  updateProductStock,
  deleteProduct,
  createPublicOrder,
  getOrderWithItemsById,
  attachStripePaymentSessionToOrder,
  markOrderPaidByPaymentSession,
  cancelOpenOrderPayment,
  cancelOpenOrderPaymentBySession,
  serializeOrderWithItems,
  syncOrderPaymentStatusFromRefunds,
  type CheckoutSessionResult,
  type Product,
  type ProductCreateInput,
  type ProductUpdateInput,
  type ProductListParams,
  type ProductListResult,
  type OrderItemInput,
  type PublicOrderCreateInput,
  type SerializedOrder,
  type SerializedOrderItem,
  type SerializedOrderPaymentAttempt,
  type SerializedOrderRefund,
  type SerializedOrderDispute,
} from "./services";

export {
  sendOrderCreatedNotifications,
  sendOrderStatusChangedNotifications,
} from "./notifications";

export {
  createStripeCheckout,
  confirmStripeCheckoutSessionForOrder,
  handleStripeCheckoutPaid,
  handleStripeCheckoutFailed,
  handleStripeCheckoutExpired,
  isAwaitingStripePayment,
  createOrderRefund,
  type OrderRefundResult,
} from "./payments";

export {
  handleStripeDisputeUpdated,
  isOpenOrderDisputeStatus,
  syncStripeDisputesForUser,
  type StripeDisputeSyncResult,
} from "./disputes";

export {
  buildPaymentAnomaliesCsv,
  buildPaymentEventsCsv,
  buildPaymentReconciliationReportFromOrders,
  getPaymentReconciliationReport,
  type PaymentReconciliationAnomaly,
  type PaymentReconciliationAttemptRecord,
  type PaymentReconciliationEvent,
  type PaymentReconciliationOrderRecord,
  type PaymentReconciliationRefundRecord,
  type PaymentReconciliationReport,
  type PaymentReconciliationSummary,
} from "./reconciliation";

export {
  SETTLEMENT_RECONCILIATION_STATUS_IGNORED,
  SETTLEMENT_RECONCILIATION_STATUS_OPEN,
  SETTLEMENT_RECONCILIATION_STATUS_RECONCILED,
  buildPaymentSettlementReportFromData,
  getPaymentSettlementReport,
  syncStripeSettlementLedger,
  updatePaymentSettlementEntries,
  type PaymentSettlementAnomaly,
  type PaymentSettlementEntryRecord,
  type PaymentSettlementLedgerSyncResult,
  type PaymentSettlementPayoutBaseRecord,
  type PaymentSettlementPayoutRecord,
  type PaymentSettlementReport,
  type PaymentSettlementSummary,
  type PaymentSettlementSyncResult,
} from "./settlements";

export {
  PAYOUT_PROVIDER_STRIPE,
  SELLER_PAYOUT_ACCOUNT_STATUS_NOT_STARTED,
  SELLER_PAYOUT_ACCOUNT_STATUS_PENDING,
  SELLER_PAYOUT_ACCOUNT_STATUS_RESTRICTED,
  SELLER_PAYOUT_ACCOUNT_STATUS_ACTIVE,
  SELLER_PAYOUT_ACCOUNT_STATUS_DISCONNECTED,
  getSellerPayoutAccountForUser,
  ensureStripePayoutAccountForUser,
  syncStripePayoutAccountForUser,
  createStripePayoutOnboardingLink,
  createStripePayoutDashboardLink,
  type SerializedSellerPayoutAccount,
} from "./payout-accounts";
