import { describe, expect, it } from "vitest";
import {
  SETTLEMENT_RECONCILIATION_STATUS_OPEN,
  buildPaymentSettlementReportFromData,
} from "@/domain/shop";

describe("buildPaymentSettlementReportFromData", () => {
  it("builds settlement summary, payout aggregation, and anomalies", () => {
    const report = buildPaymentSettlementReportFromData(
      {
        entries: [
          {
            id: "entry-1",
            externalBalanceTransactionId: "txn_1",
            provider: "STRIPE",
            externalSourceId: "ch_1",
            externalSourceType: "charge",
            type: "charge",
            reportingCategory: "charge",
            status: "available",
            amount: 10000,
            fee: 360,
            net: 9640,
            currency: "JPY",
            description: "Order charge",
            occurredAt: "2026-03-03T00:00:00.000Z",
            availableOn: "2026-03-04T00:00:00.000Z",
            reconciliationStatus: SETTLEMENT_RECONCILIATION_STATUS_OPEN,
            reconciliationNote: null,
            reconciledAt: null,
            updatedAt: "2026-03-03T00:00:00.000Z",
            orderId: "order-1",
            buyerEmail: "buyer@example.com",
            buyerName: "Alice",
            orderStatus: "PAID",
            paymentStatus: "PAID",
            refundId: null,
            refundStatus: null,
            payoutId: "payout-1",
            payoutExternalId: "po_1",
            payoutStatus: "paid",
            payoutArrivalDate: "2026-03-05T00:00:00.000Z",
            payoutCreatedAt: "2026-03-04T00:00:00.000Z",
          },
          {
            id: "entry-2",
            externalBalanceTransactionId: "txn_2",
            provider: "STRIPE",
            externalSourceId: "re_1",
            externalSourceType: "refund",
            type: "refund",
            reportingCategory: "refund",
            status: "pending",
            amount: -2000,
            fee: 0,
            net: -2000,
            currency: "JPY",
            description: "Refund",
            occurredAt: "2026-03-06T00:00:00.000Z",
            availableOn: "2026-03-07T00:00:00.000Z",
            reconciliationStatus: SETTLEMENT_RECONCILIATION_STATUS_OPEN,
            reconciliationNote: null,
            reconciledAt: null,
            updatedAt: "2026-03-06T00:00:00.000Z",
            orderId: "order-1",
            buyerEmail: "buyer@example.com",
            buyerName: "Alice",
            orderStatus: "PAID",
            paymentStatus: "PARTIALLY_REFUNDED",
            refundId: "refund-1",
            refundStatus: "SUCCEEDED",
            payoutId: null,
            payoutExternalId: null,
            payoutStatus: null,
            payoutArrivalDate: null,
            payoutCreatedAt: null,
          },
          {
            id: "entry-3",
            externalBalanceTransactionId: "txn_3",
            provider: "STRIPE",
            externalSourceId: "fee_1",
            externalSourceType: "external",
            type: "adjustment",
            reportingCategory: "adjustment",
            status: "available",
            amount: -300,
            fee: 0,
            net: -300,
            currency: "JPY",
            description: "Manual adjustment",
            occurredAt: "2026-03-08T00:00:00.000Z",
            availableOn: "2026-03-08T00:00:00.000Z",
            reconciliationStatus: SETTLEMENT_RECONCILIATION_STATUS_OPEN,
            reconciliationNote: null,
            reconciledAt: null,
            updatedAt: "2026-03-08T00:00:00.000Z",
            orderId: null,
            buyerEmail: null,
            buyerName: null,
            orderStatus: null,
            paymentStatus: null,
            refundId: null,
            refundStatus: null,
            payoutId: null,
            payoutExternalId: null,
            payoutStatus: null,
            payoutArrivalDate: null,
            payoutCreatedAt: null,
          },
        ],
        payouts: [
          {
            id: "payout-1",
            externalPayoutId: "po_1",
            provider: "STRIPE",
            status: "paid",
            amount: 9640,
            currency: "JPY",
            payoutMethod: "standard",
            description: "March payout",
            statementDescriptor: null,
            payoutCreatedAt: "2026-03-04T00:00:00.000Z",
            arrivalDate: "2026-03-05T00:00:00.000Z",
            paidAt: "2026-03-05T00:00:00.000Z",
            updatedAt: "2026-03-05T00:00:00.000Z",
          },
        ],
        localPayments: [
          {
            orderId: "order-1",
            buyerEmail: "buyer@example.com",
            buyerName: "Alice",
            totalAmount: 10000,
            currency: "JPY",
            orderStatus: "PAID",
            paymentStatus: "PARTIALLY_REFUNDED",
            paymentIntentId: "pi_1",
            paidAt: "2026-03-03T00:00:00.000Z",
          },
          {
            orderId: "order-2",
            buyerEmail: "buyer2@example.com",
            buyerName: null,
            totalAmount: 5000,
            currency: "JPY",
            orderStatus: "PAID",
            paymentStatus: "PAID",
            paymentIntentId: "pi_missing",
            paidAt: "2026-03-04T00:00:00.000Z",
          },
        ],
        localRefunds: [
          {
            refundId: "refund-1",
            orderId: "order-1",
            buyerEmail: "buyer@example.com",
            buyerName: "Alice",
            amount: 2000,
            currency: "JPY",
            refundStatus: "SUCCEEDED",
            externalRefundId: "re_1",
            externalPaymentIntentId: "pi_1",
            refundedAt: "2026-03-06T00:00:00.000Z",
          },
          {
            refundId: "refund-2",
            orderId: "order-2",
            buyerEmail: "buyer2@example.com",
            buyerName: null,
            amount: 1000,
            currency: "JPY",
            refundStatus: "SUCCEEDED",
            externalRefundId: "re_missing",
            externalPaymentIntentId: "pi_missing",
            refundedAt: "2026-03-07T00:00:00.000Z",
          },
        ],
      },
      {
        start: "2026-03-01",
        end: "2026-03-10",
        entryLimit: 20,
      }
    );

    expect(report.summary.grossCapturedAmount).toBe(10000);
    expect(report.summary.refundedAmount).toBe(2300);
    expect(report.summary.paidOutNetAmount).toBe(9640);
    expect(report.summary.unmatchedEntryCount).toBe(1);
    expect(report.payouts[0]?.linkedEntryCount).toBe(1);
    expect(report.anomalies.map((item) => item.code)).toEqual(
      expect.arrayContaining([
        "STRIPE_ENTRY_UNMATCHED",
        "LOCAL_PAYMENT_MISSING_SETTLEMENT",
        "LOCAL_REFUND_MISSING_SETTLEMENT",
      ])
    );
  });
});
