import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "@/lib/context/UserProviderWrapper";
import { InspectorWrapper } from "@/lib/context/InspectorWrapper";
import { I18nProvider } from "@/lib/i18n/context";
import ErrorFilter from "@/components/ErrorFilter";
import { ErrorBoundary } from "@/components/ui";
import "@/lib/env"; // 触发环境变量验证
import "./globals.css";
import "./globals"; // 导入 globals.ts 以立即安装错误过滤器

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <ErrorFilter />
          <InspectorWrapper>
            <UserProvider>
              <I18nProvider>{children}</I18nProvider>
            </UserProvider>
          </InspectorWrapper>
        </ErrorBoundary>
      </body>
    </html>
  );
}
